import { useState, useCallback } from 'react'
import { clsx } from 'clsx'
import { Button } from '../components/Button'

// ── Types ─────────────────────────────────────────────────────────────────────

type ExtractedColors = Record<'primary' | 'link' | 'success' | 'error', string[]>

interface TokenDef {
  cssVar: string
  label: string
  extractKey: keyof ExtractedColors | null
  secondary?: boolean
  default: string
}

interface TokenValue extends TokenDef {
  value: string
  isAuto: boolean
}

// ── Config ────────────────────────────────────────────────────────────────────

const TOKEN_DEFS: TokenDef[] = [
  { cssVar: '--color-primary',        label: 'Primary',        extractKey: 'primary', default: '#2d7a3a' },
  { cssVar: '--color-link',           label: 'Link',           extractKey: 'link',    default: '#29abe2' },
  { cssVar: '--color-success',        label: 'Success',        extractKey: 'success', default: '#5cb85c' },
  { cssVar: '--color-fail',           label: 'Fail / Alert',   extractKey: 'error',   default: '#d9534f' },
  { cssVar: '--color-dashboard-icon', label: 'Dashboard Icon', extractKey: 'primary', default: '#006b77', secondary: true },
  { cssVar: '--color-footer-bg',      label: 'Footer BG',      extractKey: null,      default: '#222222' },
  { cssVar: '--color-cp-nav',         label: 'CP Nav',         extractKey: null,      default: '#3d2b1f' },
  { cssVar: '--color-cp-nav-menu',    label: 'CP Nav Menu',    extractKey: null,      default: '#4a3728' },
  { cssVar: '--color-th-nav',         label: 'TH Nav',         extractKey: null,      default: '#3d2b1f' },
  { cssVar: '--color-tags',           label: 'Tags',           extractKey: 'link',    default: '#4a90e2', secondary: true },
]

const EXAMPLES = ['stripe.com', 'linear.app', 'github.com', 'vercel.com']

const CATEGORIES = [
  { key: 'primary' as const, label: 'Primary',    icon: '⬤' },
  { key: 'link'    as const, label: 'Link',       icon: '🔗' },
  { key: 'success' as const, label: 'Success',    icon: '✓'  },
  { key: 'error'   as const, label: 'Error / Fail', icon: '✕' },
]

// ── Helpers ───────────────────────────────────────────────────────────────────

const initTokens = (): TokenValue[] =>
  TOKEN_DEFS.map(d => ({ ...d, value: d.default, isAuto: false }))

const applyExtracted = (tokens: TokenValue[], colors: ExtractedColors): TokenValue[] =>
  tokens.map(t => {
    if (!t.extractKey) return t
    const first = colors[t.extractKey]?.[0]
    if (!first) return t
    return { ...t, value: first, isAuto: !t.secondary }
  })

const generateCSS = (tokens: TokenValue[], sourceUrl: string) =>
  [
    `/* Partner theme — generated by Color Extractor */`,
    `/* Source: ${sourceUrl || 'unknown'} */`,
    `/* ${new Date().toISOString().slice(0, 10)} */`,
    `:root {`,
    ...tokens.map(t => `  ${t.cssVar}: ${t.value.toLowerCase()};`),
    `}`,
    ``,
  ].join('\n')

// ── Component ─────────────────────────────────────────────────────────────────

export function ColorExtractor() {
  const [url, setUrl]         = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError]     = useState('')
  const [colors, setColors]   = useState<ExtractedColors | null>(null)
  const [tokens, setTokens]   = useState<TokenValue[]>(initTokens)
  const [domain, setDomain]   = useState('')
  const [copied, setCopied]   = useState('')

  const [ghToken, setGhToken] = useState('')
  const [ghRepo, setGhRepo]   = useState('tolstoy-o/DS-React-Aria')
  const [ghPath, setGhPath]   = useState('src/styles/themes/default.css')
  const [pushing, setPushing] = useState(false)
  const [pushMsg, setPushMsg] = useState<{ type: 'ok' | 'error'; text: string; url?: string } | null>(null)

  const extract = useCallback(async () => {
    const target = url.trim()
    if (!target) return
    setLoading(true); setError(''); setColors(null); setPushMsg(null)
    try {
      const res  = await fetch('/api/extract', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: target }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Failed')
      setColors(data.colors)
      setTokens(prev => applyExtracted(prev, data.colors))
      try {
        setDomain(new URL(/^https?:\/\//i.test(target) ? target : 'https://' + target).hostname)
      } catch { setDomain(target) }
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setLoading(false)
    }
  }, [url])

  const updateToken = (cssVar: string, value: string) =>
    setTokens(prev => prev.map(t => t.cssVar === cssVar ? { ...t, value, isAuto: false } : t))

  const copyHex = (hex: string) => {
    navigator.clipboard.writeText(hex.toUpperCase())
    setCopied(hex)
    setTimeout(() => setCopied(''), 1500)
  }

  const exportCSS = () => {
    const blob = new Blob([generateCSS(tokens, url)], { type: 'text/css' })
    Object.assign(document.createElement('a'), {
      href: URL.createObjectURL(blob), download: 'partner.css',
    }).click()
  }

  const push = async () => {
    const [owner, repo] = ghRepo.split('/')
    setPushing(true); setPushMsg(null)
    try {
      const res  = await fetch('/api/push', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token: ghToken, owner, repo, filePath: ghPath, content: generateCSS(tokens, url) }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Push failed')
      setPushMsg({ type: 'ok', text: 'Pushed successfully!', url: data.commitUrl })
    } catch (e: unknown) {
      setPushMsg({ type: 'error', text: e instanceof Error ? e.message : String(e) })
    } finally {
      setPushing(false)
    }
  }

  return (
    <div className="min-h-screen bg-bg-base">
      <div className="max-w-2xl mx-auto px-6 py-10">

        {/* Header */}
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-text-dark">Color Extractor</h1>
          <p className="text-text-light text-sm mt-1">
            Extract brand colors from any URL and apply them as design tokens
          </p>
        </div>

        {/* URL input */}
        <div className="bg-white rounded-xl border border-divider p-5 mb-5">
          <div className="flex gap-3">
            <input
              type="text"
              className="flex-1 h-10 px-3 rounded-md border border-input-border text-text-dark text-sm placeholder:text-text-light outline-none focus:border-primary focus:ring-2 focus:ring-primary/20 transition-shadow"
              placeholder="https://stripe.com"
              value={url}
              onChange={e => setUrl(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && extract()}
              spellCheck={false}
              autoComplete="off"
            />
            <Button onPress={extract} isDisabled={loading}>
              {loading ? 'Extracting…' : 'Extract'}
            </Button>
          </div>
          <div className="flex items-center gap-2 flex-wrap mt-3">
            <span className="text-xs text-text-light">Examples:</span>
            {EXAMPLES.map(e => (
              <button
                key={e}
                onClick={() => setUrl(e)}
                className="text-xs px-2.5 py-1 rounded-full border border-divider text-text-light hover:border-primary hover:text-text-dark transition-colors"
              >
                {e}
              </button>
            ))}
          </div>
        </div>

        {/* Error */}
        {error && (
          <div className="bg-fail/10 border border-fail/20 text-fail rounded-lg px-4 py-3 text-sm mb-5">
            {error}
          </div>
        )}

        {colors && (
          <>
            {/* Site meta */}
            <div className="flex items-center gap-2 mb-4">
              <img
                src={`https://www.google.com/s2/favicons?domain=${domain}&sz=32`}
                className="w-5 h-5 rounded"
                onError={e => (e.currentTarget.style.display = 'none')}
                alt=""
              />
              <span className="text-sm text-text-light">{domain}</span>
            </div>

            {/* Category swatches */}
            <div className="grid grid-cols-2 gap-3 mb-5">
              {CATEGORIES.map(({ key, label, icon }) => {
                const list = colors[key] || []
                return (
                  <div key={key} className="bg-white rounded-xl border border-divider p-4">
                    <div className="flex items-center gap-2 mb-3">
                      <span>{icon}</span>
                      <span className="text-xs font-semibold text-text-light uppercase tracking-wide">{label}</span>
                    </div>
                    <div className="flex gap-2 flex-wrap">
                      {list.length === 0 ? (
                        <span className="text-xs text-text-light italic">not found</span>
                      ) : list.map(hex => (
                        <button
                          key={hex}
                          title={copied === hex ? 'Copied!' : `Click to copy ${hex.toUpperCase()}`}
                          onClick={() => copyHex(hex)}
                          className="group flex flex-col items-center gap-1"
                        >
                          <div
                            className="w-10 h-10 rounded-lg border border-black/10 transition-transform group-hover:-translate-y-0.5 group-hover:shadow-md"
                            style={{ background: hex }}
                          />
                          <span className="text-[10px] font-mono text-text-light group-hover:text-text-dark">
                            {copied === hex ? '✓' : hex.toUpperCase()}
                          </span>
                        </button>
                      ))}
                    </div>
                  </div>
                )
              })}
            </div>

            {/* Token mapping */}
            <div className="bg-white rounded-xl border border-divider p-5 mb-3">
              <h2 className="text-xs font-bold text-text-light uppercase tracking-widest mb-4">
                Design Tokens — partner.css
              </h2>
              <div className="divide-y divide-divider">
                {tokens.map(token => (
                  <div key={token.cssVar} className="flex items-center justify-between py-3 gap-3">
                    <div className="min-w-0 flex-1">
                      <div className="text-sm font-semibold text-text-dark">{token.label}</div>
                      <div className="font-mono text-[11px] text-text-light">{token.cssVar}</div>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      {token.isAuto && (
                        <span className="text-[10px] font-bold uppercase tracking-wide text-primary bg-primary/10 border border-primary/20 rounded px-1.5 py-0.5">
                          auto
                        </span>
                      )}
                      <label className="relative cursor-pointer block" title="Click to change">
                        <div
                          className="w-8 h-8 rounded-lg border border-black/10 transition-transform hover:scale-110 hover:shadow-md"
                          style={{ background: token.value }}
                        />
                        <input
                          type="color"
                          value={token.value}
                          className="absolute inset-0 opacity-0 cursor-pointer w-full h-full p-0 border-0"
                          onChange={e => updateToken(token.cssVar, e.target.value)}
                        />
                      </label>
                      <input
                        type="text"
                        value={token.value.toUpperCase()}
                        maxLength={7}
                        spellCheck={false}
                        onChange={e => {
                          const v = e.target.value
                          if (/^#[0-9a-f]{6}$/i.test(v)) updateToken(token.cssVar, v)
                        }}
                        className="w-20 h-8 px-2 rounded-md border border-input-border text-xs font-mono text-text-dark outline-none focus:border-primary transition-colors"
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* GitHub */}
            <div className="bg-white rounded-xl border border-divider p-5 mb-3">
              <h2 className="text-xs font-bold text-text-light uppercase tracking-widest mb-4">GitHub</h2>
              <div className="space-y-3">
                {([
                  { label: 'Token',      val: ghToken, set: setGhToken, type: 'password' },
                  { label: 'Repository', val: ghRepo,  set: setGhRepo,  type: 'text'     },
                  { label: 'File path',  val: ghPath,  set: setGhPath,  type: 'text'     },
                ] as const).map(({ label, val, set, type }) => (
                  <div key={label}>
                    <label className="block text-xs font-semibold text-text-light mb-1">{label}</label>
                    <input
                      type={type}
                      value={val}
                      onChange={e => set(e.target.value)}
                      spellCheck={false}
                      autoComplete="off"
                      className="w-full h-9 px-3 rounded-md border border-input-border text-sm font-mono text-text-dark outline-none focus:border-primary focus:ring-2 focus:ring-primary/20 transition-shadow"
                    />
                  </div>
                ))}
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-3">
              <Button variant="secondary" className="flex-1" onPress={exportCSS}>
                ⬇ Download CSS
              </Button>
              <Button className="flex-1" onPress={push} isDisabled={pushing}>
                {pushing ? 'Pushing…' : '↑ Push to GitHub'}
              </Button>
            </div>

            {pushMsg && (
              <div className={clsx(
                'mt-3 rounded-lg px-4 py-3 text-sm text-center border',
                pushMsg.type === 'ok'
                  ? 'bg-success/10 text-success border-success/20'
                  : 'bg-fail/10 text-fail border-fail/20',
              )}>
                {pushMsg.text}
                {pushMsg.url && (
                  <a href={pushMsg.url} target="_blank" rel="noreferrer" className="ml-2 underline">
                    View commit →
                  </a>
                )}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  )
}
